import crypto from "node:crypto";
import { envInteger, envList } from "./daemon-security-helpers.mjs";

export function createDaemonConfig() {
  const configuredPairingToken = process.env.SOUNDBRIDGE_PAIRING_TOKEN?.trim();
  const maxParameterEventsPerRequest = envInteger("SOUNDBRIDGE_MAX_PARAMETER_EVENTS_PER_REQUEST", 4096);
  const maxPluginStateBytes = envInteger("SOUNDBRIDGE_MAX_PLUGIN_STATE_BYTES", 384 * 1024);
  const maxPluginStateEnvelopeBytes = envInteger("SOUNDBRIDGE_MAX_PLUGIN_STATE_ENVELOPE_BYTES", 1024 * 1024);

  return {
    HOST: process.env.SOUNDBRIDGE_HOST ?? "127.0.0.1",
    PORT: Number(process.env.SOUNDBRIDGE_PORT ?? 47370),
    PAIRING_TOKEN: configuredPairingToken || crypto.randomBytes(18).toString("base64url"),
    PAIRING_TOKEN_IS_EPHEMERAL: !configuredPairingToken,
    PROTOCOL_VERSION: "0.1.0",
    SESSION_TTL_MS: envInteger("SOUNDBRIDGE_SESSION_TTL_MS", 30 * 60 * 1000),
    MAX_SESSIONS_PER_ORIGIN: envInteger("SOUNDBRIDGE_MAX_SESSIONS_PER_ORIGIN", 8),
    MAX_INSTANCES_PER_SESSION: envInteger("SOUNDBRIDGE_MAX_INSTANCES_PER_SESSION", 8),
    MAX_TOTAL_INSTANCES: envInteger("SOUNDBRIDGE_MAX_TOTAL_INSTANCES", 32),
    MAX_WEBSOCKET_MESSAGE_BYTES: envInteger("SOUNDBRIDGE_MAX_WEBSOCKET_MESSAGE_BYTES", 1024 * 1024),
    MAX_TOTAL_SESSIONS: envInteger("SOUNDBRIDGE_MAX_TOTAL_SESSIONS", 64),
    MAX_AUDIO_CHANNELS: envInteger("SOUNDBRIDGE_MAX_AUDIO_CHANNELS", 32),
    MAX_PLUGIN_BUSES: envInteger("SOUNDBRIDGE_MAX_PLUGIN_BUSES", 32),
    MAX_BLOCK_SIZE: envInteger("SOUNDBRIDGE_MAX_BLOCK_SIZE", 8192),
    MAX_MIDI_EVENTS_PER_REQUEST: envInteger("SOUNDBRIDGE_MAX_MIDI_EVENTS_PER_REQUEST", 4096),
    MAX_NOTE_EXPRESSION_TEXT_BYTES: Math.min(envInteger("SOUNDBRIDGE_MAX_NOTE_EXPRESSION_TEXT_BYTES", 256), 1024),
    MAX_PARAMETER_EVENTS_PER_REQUEST: maxParameterEventsPerRequest,
    MAX_AUTOMATION_CURVE_POINTS: Math.min(
      envInteger("SOUNDBRIDGE_MAX_AUTOMATION_CURVE_POINTS", 256),
      256,
      maxParameterEventsPerRequest
    ),
    MAX_AUTOMATION_LANES_PER_INSTANCE: Math.min(
      envInteger("SOUNDBRIDGE_MAX_AUTOMATION_LANES_PER_INSTANCE", 128),
      1024
    ),
    MAX_AUTOMATION_LANE_POINTS: Math.min(
      envInteger("SOUNDBRIDGE_MAX_AUTOMATION_LANE_POINTS", 4096),
      4096
    ),
    MAX_EDITORS_PER_SESSION: envInteger("SOUNDBRIDGE_MAX_EDITORS_PER_SESSION", 8),
    MAX_TOTAL_EDITORS: envInteger("SOUNDBRIDGE_MAX_TOTAL_EDITORS", 32),
    EDITOR_SESSION_TTL_MS: envInteger("SOUNDBRIDGE_EDITOR_SESSION_TTL_MS", 10 * 60 * 1000),
    MAX_FILE_GRANTS_PER_SESSION: envInteger("SOUNDBRIDGE_MAX_FILE_GRANTS_PER_SESSION", 8),
    MAX_FILE_GRANTS_PER_INSTANCE: Math.max(
      1,
      Math.min(envInteger("SOUNDBRIDGE_MAX_FILE_GRANTS_PER_INSTANCE", 8), 64)
    ),
    MAX_TOTAL_FILE_GRANTS: envInteger("SOUNDBRIDGE_MAX_TOTAL_FILE_GRANTS", 64),
    FILE_GRANT_TTL_MS: envInteger("SOUNDBRIDGE_FILE_GRANT_TTL_MS", 10 * 60 * 1000),
    MAX_FILE_GRANT_PATH_BYTES: Math.min(envInteger("SOUNDBRIDGE_MAX_FILE_GRANT_PATH_BYTES", 4096), 4096),
    MAX_FILE_GRANT_DISPLAY_NAME_BYTES: Math.min(
      envInteger("SOUNDBRIDGE_MAX_FILE_GRANT_DISPLAY_NAME_BYTES", 160),
      256
    ),
    MAX_PLUGIN_PARAMETERS: envInteger("SOUNDBRIDGE_MAX_PLUGIN_PARAMETERS", 1024),
    MAX_PLUGIN_PRESETS: Math.min(envInteger("SOUNDBRIDGE_MAX_PLUGIN_PRESETS", 256), 256),
    MAX_PLUGIN_PROGRAM_LISTS: Math.min(envInteger("SOUNDBRIDGE_MAX_PLUGIN_PROGRAM_LISTS", 256), 256),
    MAX_PLUGIN_PROGRAMS: Math.min(envInteger("SOUNDBRIDGE_MAX_PLUGIN_PROGRAMS", 256), 256),
    MAX_PLUGIN_NOTE_EXPRESSIONS: Math.min(envInteger("SOUNDBRIDGE_MAX_PLUGIN_NOTE_EXPRESSIONS", 256), 256),
    MAX_PLUGIN_PARAMETER_TEXT_BYTES: envInteger("SOUNDBRIDGE_MAX_PLUGIN_PARAMETER_TEXT_BYTES", 160),
    MAX_PLUGIN_METADATA_TEXT_BYTES: envInteger("SOUNDBRIDGE_MAX_PLUGIN_METADATA_TEXT_BYTES", 256),
    MAX_PLUGIN_STATE_BYTES: maxPluginStateBytes,
    MAX_PLUGIN_PROGRAM_DATA_BYTES: Math.min(
      envInteger("SOUNDBRIDGE_MAX_PLUGIN_PROGRAM_DATA_BYTES", 384 * 1024),
      maxPluginStateBytes
    ),
    MAX_PLUGIN_STATE_ENVELOPE_BYTES: maxPluginStateEnvelopeBytes,
    MAX_PLUGIN_PROGRAM_DATA_ENVELOPE_BYTES: maxPluginStateEnvelopeBytes,
    MAX_PLUGIN_LATENCY_SAMPLES: envInteger("SOUNDBRIDGE_MAX_PLUGIN_LATENCY_SAMPLES", 1_048_576),
    MAX_PLUGIN_TAIL_SAMPLES: envInteger("SOUNDBRIDGE_MAX_PLUGIN_TAIL_SAMPLES", 1_048_576),
    MAX_TRANSPORT_TEMPO_BPM: envInteger("SOUNDBRIDGE_MAX_TRANSPORT_TEMPO_BPM", 960),
    MAX_TRANSPORT_POSITION_MUSIC: envInteger("SOUNDBRIDGE_MAX_TRANSPORT_POSITION_MUSIC", 1_000_000_000),
    MAX_TRANSPORT_SAMPLE_POSITION: Number.MAX_SAFE_INTEGER,
    MAX_PAIR_ATTEMPTS_PER_CONNECTION: envInteger("SOUNDBRIDGE_MAX_PAIR_ATTEMPTS", 5),
    MIN_SAMPLE_RATE: 8000,
    MAX_SAMPLE_RATE: 384000,
    ALLOWED_ORIGINS: envList("SOUNDBRIDGE_ALLOWED_ORIGINS"),
    FILE_GRANT_ROOTS: envList("SOUNDBRIDGE_FILE_GRANT_ROOTS"),
    ALLOW_BROWSER_FILE_GRANT_PATHS: process.env.SOUNDBRIDGE_FILE_GRANT_ALLOW_BROWSER_PATHS === "1"
  };
}
